// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"todo-server/internal/dao/internal"
)

// todoDao is the data access object for the table todo.
// You can define custom methods on it to extend its functionality as needed.
type todoDao struct {
	*internal.TodoDao
}

var (
	// Todo is a globally accessible object for table todo operations.
	Todo = todoDao{internal.NewTodoDao()}
)

// Add your custom methods and functionality below.
