// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package todo

import (
	"todo-server/api/todo"
)

type ControllerV1 struct{}

func NewV1() todo.ITodoV1 {
	return &ControllerV1{}
}
